//
// Created by bonychops on 11/12/21.
//

#ifndef PROG_GAME_DEFINE_H
#define PROG_GAME_DEFINE_H

#define FRAME 20
#define WINDOW_W 640
#define WINDOW_H 480

#define COLLISION_POINTS_ACCURATE 8
#define COLLISION_CALC_ACCURATE 1
#define COLLISIONS_PER_OBJECT 10
#define BLOCK_RC_SIZE 32

#define POWERS_NUM 2
#define IMAGE_MAX 10000

#define SEARCH_AROUND_ACCURATE 8
#define SEARCH_AROUND_DISTANCE 10

#define GRAVITY -0.00005

#define PARTICLES 20

#define DEBUG false

#define SHIFT_KEY 112
#endif //PROG_GAME_DEFINE_H
